.*: Assembler messages:
.*:9: Error: illegal operands `amocas.q a1,a0,\(a0\)'
.*:10: Error: illegal operands `amocas.q a0,a1,\(a0\)'
.*:11: Error: illegal operands `amocas.q.aq a1,a0,\(a0\)'
.*:12: Error: illegal operands `amocas.q.aq a0,a1,\(a0\)'
.*:13: Error: illegal operands `amocas.q.rl a1,a0,\(a0\)'
.*:14: Error: illegal operands `amocas.q.rl a0,a1,\(a0\)'
.*:15: Error: illegal operands `amocas.q.aqrl a1,a0,\(a0\)'
.*:16: Error: illegal operands `amocas.q.aqrl a0,a1,\(a0\)'
